[package]
name = "nazori"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = "0.39.2"
ordered-float = { version = "5.1.0", default-features = false }
kasane-logic = { git = "https://github.com/AirBee-Project/Kasane-Logic.git", branch = "main" ,features = ["openapi","serde"]}

[dev-dependencies]
insta = { version = "1.47.2", features = ["glob"] }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook","run-cargo-clippy","run-cargo-fmt"]
